apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disable-default-sa-automount.yaml
  - no-added-capabilities.yaml
  - no-hostpath.yaml
  - no-hostports.yaml
  - no-net-raw.yaml
  - restrict-default-namespace.yaml
