---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgCcr8rxBucLsXPVorG6rVXM2HeJJFB6yr1C0U7DNVIdtZy5ZcKVwGIg5VpxQ2prW8d7MX65J5vqlGslcS55vr2uq9/PrVImCIBll8kJYVUZ1GVI/su/YKbG7ZNjx+di1M4qXbl+JPsr8jXFWATKVviiq8MQwODKA3o0gJjgislUTBBAx4k+oPpmvdXb1FQ7D3+IvLDbEMqRou0I6uaviPe6oigIWahuBrhezu7CP7Pf/Fm9IZaNrwcQVHPCfZmaiCMKEfdRH6Vo8VB7DrtzuntLPROFumO1+yunH2PddanDfWi1B0M9j0LJIfqbcTXmGYWuU6gUet3kYf0tANEW1hocd4rUoApthKWOr+JWNHmwTZce+b/V2YsvFBUzh6Y7WC11rR4i4HXvz54aaAJpD1OdqyvF1msjiyR5+37dEJUyv3vcE6CN4kNziN08MVWa6rEFme2/Idw83Plovg9fKeZjL0Obt0NQ7Wuo6ynaB1t/AwZ32gL6km6zNKGx2HGXqfQiNzYp0P7L1Y19zXCHJL86+yU3PL/TO3vFtZsYEEGGAvzP1JAULCHP88AC+TbOy4QmM44LM5iCp2xSAmRTExmkEgy+z7nGbP14Q/rxhdLgcbTVjJ+AA1Sg8zM8xkkBJii6BBAe6BtxR5rrsOSmgxbZYmDDS6O7fdzlueCbesUoCMrUL6quPnktc5XCct0sNfrFYXCVv0A=
    admin-password: AgA5jilmfgU+IWfBA7XptrdRWwxVHDXhihtw4ZEKsJejoHhXbJPvOCLX3l+yEtWBEdR2q+WMwlZfc6ZvfC9lybgvr/6EUMNSyVaHBk7icgUmnLZ3sPhvLolhRgTgcSEJz9EOxjRdGsIyRYrgy47NfU2DX28xtwPbGCbL0Q/N3dm6en+erUjLNDXrkdvP6BG401kNVOTDhkMBKbZVioCS9HWOrFerLmDFeswW8sripue+28rcV0YRE/WMhEIDSGC4KGrfUugilgAoZG8IDpqYGiuBIHpdDowh/qRu9uWlW0JhvtKN3ze5SPoNJy1FI2h6JjlH7COGxbJwQJoUe79sycB3eRElBT9FrYl35dBZlXNtMSD8hqUqHxAblzncsvnSywhhsbXglF0ugYJ+mRxZsLftkwKXkailfVZsMCYTtFbpzjNLLddgJFNhuteE9z0gza5q6AvSReb6TK4xy/3R0rrYvIGeOfDHorKQo1C9opaMWbj4x2/jQlUQwqEaSBAe+lH9y7Rt8BSEGUcfnp014vNs1msbehcjprqXnwglNvgxFwX8+TQ+1dzli9/+SBUbpndcGFsO+zl+e7KKskLYD9X8J3iskfXQZGrEoDzyJaj1uZsMCxWUhHVYbGzahXN0j3C4h3dq4d0PgvROS+kJ9aXtbpVSl808/xrt6l2i3iHzLTPFBHMy69F6iW0cwO8tCVtRrhmxhxUByXIFDgJANbqjPhmmhkX0JDGm7vIzv8GOmg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
