apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - linkerd.siegfrid.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: web
          port: 8084

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: linkerd-viz-auth
  namespace: linkerd-viz
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: linkerd-viz
  basicAuth:
    users:
      name: linkerd-viz-auth

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkerd-viz-auth
  namespace: linkerd-viz
spec:
  encryptedData:
    .htpasswd: AgC4zsoS2Bpr8qcOT9k8qWVyjLCJJuWPiWv26CMoMJyimNL2Bzvvb67wtjMf2hmPZdfV8dUKfDR/vnT7fZSyqWn5sMWO7v9t0GeZV0O8Lo9btHyuAIQK2H4778QDUmIdGSd6NRz5UcnLsrE4F5igBkSONoO1X7ywkuR+r1w/HOxk/Gpe9MXhQs4ocfCVT6SHkonALRiGUZQ9DeQXLf6pan6lkCQMsBqzvi8YrODf//Zu9LOOBt3lm0jU+6yiKpc/BTvI/S5iJ7eOpUhjzgCKVGnWA84jtp8gnSzjk4GYl35vVflvZlfaSlpxFCzk7APL5GehuKC5UloNdk6aTAtzd5osFh9jLJGbm21jAXi4bmbrXhgAbz0XO/0wuY7IABEGxu3Ff0/VsCweQ5VkUPQ/9Is6pflVBF1FSpuoxTlCnvjVLSzXINVkvLu461zQWUhtMUjPgJUh+OKrqBFUKP5+vmvGErWu62Xr4n+R/FmxCikvmz3GkOK1CBiV0r3yo0vlQCDUTLhVVrT9FHccbcqbMISsYyxDmfxKbuhV5q8U4jUHXonBtHLFUa/HxD1JTw6kABMhsHfipoZ/uCJgxiviMPuQ/3+9Wlg2mzmzemqDUnZ+9GZZ158xzv6ORytQKlFrhQPA5ulPRPJcvPyYu+yIyQiaGMhzA82gPLpHfJPV1VUDjO9qoCFmyoekGrQL/0sklkSQSmf9NkyS6H9DaUC2OONSyZSEfAIqL3Pw1BWAvxyR4eTsdOnY5nvN
  template:
    metadata:
      name: linkerd-viz-auth
      namespace: linkerd-viz
    type: Opaque
