---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBf/SivVS5SyGntHf6g+TmgeqxLExuF7LCWvMMIyH+OLQGo4Ez70I7dmvmzADJBZhmXmR+vczkOgqOnnkBxdh8qNETSD20lzOJB7TaIKiYxwr3uYUT1HBFTxFx1wkfpOS0NyPRv1fPb4hETTZw7+59PYgDc1YoXX9h+ImulLqnXGAuBJckSRDSzWoEZ4EulceXRFh+qaoEOE1lAj0V6bupMZ6b48ilto99i9mnezOfDjAGGdf4ZzlIvH//MYsijHZ1opzI0uHfHHGJ6/6c2jq6kQQuE1D0cCCcbXxMYMk+S/11tBe0bgc9I3/tQI1jyKbGFZCM5C7llbCl0IGcM87buJ2KsGSIE1MZIGR7054iPIXTaIOG0YEIhNZtE7u27dtU0xI8O7V346vKhexZBobBuuCeHQJ4+Bx4p/USX9pq52tA9vTEemy6X48RA4IS+ht2TQG/DBKoiy/78zFYtlvc9dSHSONhobR9FnutXJygw/umkjp8pAgDNq7ObWHDKWibs7uBvjoYr3xFWdC+WOfoQCF5jYJmat3mtrwbI5wTzR86/QtS61k+D6S2UHMGVhAOI4XpgwFWb+5go310pL3T4n43XJHVuKhLhMFYSKsHYqVPYkuMWkNpGy65HTCvc9pbJK2IOsqqj0ZIIVp+UfYEI2udqXC++7Yl2Z/Ll0G5r2/M4RSpnwcSb8AxUP416xbju6FIp7bCpupzMp2rwxXJtoifO+tyfU6iLUi1kshYng+ho0aaO0Gcx
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
