---
- name: Apply sealed secrets key
  hosts: all
  become: true
  tasks:
    - name: Ensure environmental variables are set
      ansible.builtin.fail:
        msg: "SEALED_SECRETS_CRT or SEALED_SECRETS_KEY is not set in the environment."
      when: lookup('env', 'SEALED_SECRETS_CRT') == "" or lookup('env', 'SEALED_SECRETS_KEY') == ""

    - name: Apply sealed secrets key
      ansible.builtin.shell: |
        cat <<EOF | k3s kubectl apply -f -
        apiVersion: v1
        kind: Secret
        metadata:
          name: master-key
          namespace: kube-system
          labels:
            sealedsecrets.bitnami.com/sealed-secrets-key: "active"
        type: kubernetes.io/tls
        data:
          tls.crt: "{{ lookup('env', 'SEALED_SECRETS_CRT') }}"
          tls.key: "{{ lookup('env', 'SEALED_SECRETS_KEY') }}"
        EOF
      args:
        executable: /bin/bash
      no_log: true # Important! This hides the secrets from your ansible console output
