---
- name: Update K3s config and restart
  hosts: all
  become: true

  tasks:
    - name: Copy K3s config files
      copy:
        src: files/k3s/
        dest: /etc/rancher/k3s/
        owner: root
        group: root
        mode: "0644"
      notify: Restart k3s

  handlers:
    - name: Restart k3s
      systemd:
        name: k3s
        state: restarted
